#!/usr/bin/env python3
"""Generate the allocation-free runtime table from the pinned emoticon snapshot."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify the checked-in table")
    args = parser.parse_args()
    source = ROOT / "data/emoticons"
    groups = json.loads((source / "emoticons.json").read_text())
    aliases = {}
    for group in groups:
        for alias in group["emoticons"]:
            if not alias.isascii() or not alias or alias in aliases:
                raise ValueError(f"Invalid or duplicate emoticon: {alias!r}")
            aliases[alias] = group["emoji"]
    notice = "\n".join(("// " + line).rstrip() for line in (source / "LICENSE").read_text().splitlines())
    lines = [
        "// Generated by tools/emoticons/generate_table.py; do not edit.",
        "// Source: wooorm/emoticon 4.1.0, commit 5b43e4c3e6fe43601790cc888a5e655fa9c1ffc4.",
        notice,
        "",
        f"pub(super) const MAX_EMOTICON_LEN: usize = {max(map(len, aliases))};",
        "",
        "pub(super) const EMOTICON_RULES: &[(&str, &str)] = &[",
    ]
    for alias, emoji in sorted(aliases.items()):
        lines.append(f"    ({json.dumps(alias, ensure_ascii=False)}, {json.dumps(emoji, ensure_ascii=False)}),")
    lines.append("];\n")
    target = ROOT / "src/autocorrect/emoticon/table.rs"
    target.parent.mkdir(exist_ok=True)
    generated = "\n".join(lines)
    if args.check:
        if target.read_text() != generated:
            raise SystemExit("Emoticon table is stale; run tools/emoticons/generate_table.py")
    else:
        target.write_text(generated)


if __name__ == "__main__":
    main()
